const globals = require('globals');
const js = require('@eslint/js');
const prettier = require('eslint-config-prettier');
const unicorn = require('eslint-plugin-unicorn').default;
const jsdoc = require('eslint-plugin-jsdoc');

module.exports = [
  js.configs.all,
  unicorn.configs['flat/recommended'],
  {
    plugins: { jsdoc },
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      // --- STRICT BEST PRACTICES ---
      'no-var': 'error',
      'prefer-const': 'error',
      strict: ['error', 'global'],
      'no-console': 'error',
      'no-alert': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-param-reassign': 'error',
      'no-shadow': 'error',
      'no-with': 'error',
      'no-caller': 'error',
      'no-iterator': 'error',
      'no-proto': 'error',
      'no-void': 'error',
      'no-script-url': 'error',
      'no-new-wrappers': 'error',
      'no-new': 'error',
      'no-multi-str': 'error',
      'no-native-reassign': 'error',
      'no-octal-escape': 'error',
      'no-constructor-return': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-else-return': 'error',
      'no-nested-ternary': 'error',
      'no-lonely-if': 'error',
      'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
      'no-continue': 'error',
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'grouped-accessor-pairs': 'error',
      'no-constructor-return': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      curly: ['error', 'all'],
      'dot-notation': 'error',
      radix: 'error',
      'prefer-template': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-spread': 'error',
      'prefer-rest-params': 'error',
      'prefer-destructuring': 'error',
      'array-callback-return': 'error',
      'no-array-constructor': 'error',
      'no-new-object': 'error',
      'no-new-array': 'off', // unicorn handles this
      'prefer-object-spread': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-rename': 'error',
      'object-shorthand': 'error',
      'no-useless-constructor': 'error',
      'no-dupe-class-members': 'error',

      // --- VARIABLES ---
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-use-before-define': ['error', { functions: false, classes: true }],
      'no-restricted-globals': ['error', 'event', 'name', 'length', 'closed', 'open'],
      'no-implicit-globals': 'error',
      'block-scoped-var': 'error',
      'no-catch-shadow': 'error',
      'no-label-var': 'error',
      'no-restricted-syntax': [
        'error',
        { selector: 'ForInStatement', message: 'for-in loops are slow and error-prone; use for-of or Object.keys' },
        { selector: 'LabeledStatement', message: 'Labels are confusing' },
      ],

      // --- COMPLEXITY ---
      complexity: ['error', 15],
      'max-depth': ['error', 4],
      'max-params': ['error', 4],
      'max-lines-per-function': ['error', { max: 50, skipBlankLines: true, skipComments: true }],
      'max-statements': ['error', 20],
      'max-nested-callbacks': ['error', 3],
      'max-lines': ['error', { max: 3000, skipBlankLines: true, skipComments: true }],

      // --- STYLE ---
      'no-extra-semi': 'error',
      'no-irregular-whitespace': 'error',
      'no-unreachable': 'error',
      'no-unsafe-negation': 'error',
      'no-cond-assign': ['error', 'always'],
      'no-constant-condition': 'error',
      'no-multi-spaces': 'error',
      'no-trailing-spaces': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      'eol-last': ['error', 'always'],
      'lines-around-comment': [
        'error',
        { beforeBlockComment: true, beforeLineComment: true, allowBlockStart: true, allowObjectStart: true },
      ],
      'newline-per-chained-call': ['error', { ignoreChainWithDepth: 2 }],
      'padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: '*', next: 'return' },
        { blankLine: 'always', prev: 'multiline-block-like', next: '*' },
        { blankLine: 'always', prev: '*', next: 'function' },
        { blankLine: 'always', prev: 'function', next: '*' },
      ],
      'one-var': ['error', 'never'],
      'wrap-iife': 'error',
      'no-magic-numbers': [
        'error',
        {
          ignore: [-1, 0, 1, 2],
          ignoreArrayIndexes: true,
          enforceConst: true,
          detectObjects: false,
        },
      ],

      // --- CLASSES ---
      'class-methods-use-this': 'off', // too strict for manager pattern
      'consistent-this': 'error',
      'func-style': ['error', 'declaration', { overrides: { ArrowFunctionExpression: 'always' } }],
      'init-declarations': ['error', 'always'],
      'new-cap': 'error',
      'no-this-before-super': 'error',

      // --- JSDOC ---
      'jsdoc/require-jsdoc': [
        'error',
        {
          require: {
            FunctionDeclaration: true,
            MethodDefinition: true,
            ClassDeclaration: true,
            ArrowFunctionExpression: false,
            FunctionExpression: false,
          },
          contexts: ['MethodDefinition'],
        },
      ],
      'jsdoc/require-param': 'error',
      'jsdoc/require-returns': 'error',
      'jsdoc/check-types': 'error',
      'jsdoc/require-param-type': 'error',
      'jsdoc/require-returns-type': 'error',
      'jsdoc/require-param-description': 'error',
      'jsdoc/require-returns-description': 'error',
      'jsdoc/check-param-names': 'error',
      'jsdoc/check-tag-names': 'error',
      'jsdoc/valid-types': 'error',
      'jsdoc/no-undefined-types': 'error',
      'jsdoc/tag-lines': ['error', 'any', { startLines: 1 }],

      // --- UNICORN OVERRIDES (promoted to error) ---
      'unicorn/prefer-ternary': 'error',
      'unicorn/no-null': 'off', // conflicts with codebase patterns
      'unicorn/prefer-string-slice': 'error',
      'unicorn/prefer-node-protocol': 'off', // CommonJS project
      'unicorn/catch-error-name': 'error',
      'unicorn/prevent-abbreviations': 'off', // too noisy for existing code
      'unicorn/no-array-for-each': 'error',
      'unicorn/no-array-reduce': 'error',
      'unicorn/no-for-loop': 'error',
      'unicorn/no-lonely-if': 'error',
      'unicorn/no-nested-ternary': 'error',
      'unicorn/no-new-buffer': 'error',
      'unicorn/no-process-exit': 'error',
      'unicorn/no-static-only-class': 'error',
      'unicorn/no-useless-undefined': 'error',
      'unicorn/prefer-add-event-listener': 'error',
      'unicorn/prefer-array-find': 'error',
      'unicorn/prefer-array-flat-map': 'error',
      'unicorn/prefer-array-index-of': 'error',
      'unicorn/prefer-array-some': 'error',
      'unicorn/prefer-date-now': 'error',
      'unicorn/prefer-includes': 'error',
      'unicorn/prefer-modern-math-apis': 'error',
      'unicorn/prefer-native-coercion-functions': 'error',
      'unicorn/prefer-number-properties': 'error',
      'unicorn/prefer-optional-catch-binding': 'error',
      'unicorn/prefer-prototype-methods': 'error',
      'unicorn/prefer-reflect-apply': 'error',
      'unicorn/prefer-regexp-test': 'error',
      'unicorn/prefer-set-has': 'error',
      'unicorn/prefer-string-starts-ends-with': 'error',
      'unicorn/prefer-string-trim-start-end': 'error',
      'unicorn/prefer-type-error': 'error',
      'unicorn/throw-new-error': 'error',
      'unicorn/explicit-length-check': 'error',
      'unicorn/no-zero-fractions': 'error',
      'unicorn/prefer-dom-node-append': 'error',
      'unicorn/prefer-dom-node-remove': 'error',
      'unicorn/prefer-dom-node-text-content': 'error',
      'unicorn/prefer-logical-operator-over-ternary': 'error',
      'unicorn/prefer-math-trunc': 'error',
      'unicorn/prefer-negative-index': 'error',
      'unicorn/prefer-query-selector': 'error',
      'unicorn/prefer-switch': 'error',
      'unicorn/prefer-top-level-await': 'off', // not ESM
      'unicorn/consistent-function-scoping': 'error',
      'unicorn/filename-case': 'off',
      'unicorn/numeric-separators-style': 'error',
      'unicorn/prefer-module': 'off', // CommonJS
      'unicorn/no-array-callback-reference': 'off', // conflicts with manager pattern
      'unicorn/no-await-expression-member': 'error',
      'unicorn/no-keyword-prefix': 'off',
      'unicorn/no-unreadable-array-destructuring': 'error',
      'unicorn/no-unused-properties': 'off',
      'unicorn/number-literal-case': 'error',
      'unicorn/escape-case': 'error',
      'unicorn/import-style': 'off',
      'unicorn/no-abusive-eslint-disable': 'error',
      'unicorn/no-hex-escape': 'error',
      'unicorn/no-instanceof-array': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-new-array': 'error',
      'unicorn/no-object-as-default-parameter': 'error',
      'unicorn/no-thenable': 'error',
      'unicorn/no-unnecessary-await': 'error',
      'unicorn/no-unnecessary-polyfills': 'error',
      'unicorn/no-useless-fallback-in-spread': 'error',
      'unicorn/no-useless-length-check': 'error',
      'unicorn/no-useless-promise-resolve-reject': 'off',
      'unicorn/no-useless-spread': 'error',
      'unicorn/prefer-array-flat': 'error',
      'unicorn/prefer-blob-reading-methods': 'error',
      'unicorn/prefer-code-point': 'error',
      'unicorn/prefer-event-target': 'error',
      'unicorn/relative-url-style': 'error',
      'unicorn/require-array-join-separator': 'error',
      'unicorn/switch-case-braces': 'error',
      'unicorn/text-encoding-identifier-case': 'error',

      // --- RELAXATIONS FOR GAME CODE ---
      'max-classes-per-file': 'off', // game has many manager classes
      'no-ternary': 'off', // ternaries are idiomatic in game logic
      'no-undefined': 'off', // undefined checks are standard JS
      'no-implicit-coercion': 'off', // +string is fine for parsing
      'no-empty-function': 'off', // intentional no-op methods
      'no-underscore-dangle': 'off', // private convention
      'no-bitwise': 'off', // game code may use bitwise
      'camelcase': 'off', // existing snake_case constants
      'func-names': 'off',
      'no-magic-numbers': 'off', // game constants are inherently magic
      'max-lines-per-function': 'off', // game methods are naturally long
      'max-statements': 'off',
      'max-params': ['error', 5], // manager constructors take deps objects
      'max-depth': ['error', 5],
      complexity: ['error', 20],
      'no-continue': 'off',
      'no-plusplus': 'off',
      'one-var': 'off',
      'func-style': 'off',
      'init-declarations': 'off',
      'consistent-this': 'off',
      'no-undef-init': 'off',
      'no-restricted-globals': 'off',
      'no-implicit-globals': 'off',
      'block-scoped-var': 'off',
      'no-catch-shadow': 'off',
      'no-label-var': 'off',
      'lines-around-comment': 'off',
      'padding-line-between-statements': 'off',
      'newline-per-chained-call': 'off',
      'no-new': 'off', // needed for managers
      'no-useless-constructor': 'off', // manager constructors are intentional
      'no-dupe-class-members': 'off',
      'class-methods-use-this': 'off',
      'default-param-last': 'off',
      'grouped-accessor-pairs': 'off',
      'prefer-destructuring': 'off',
      'prefer-rest-params': 'off',
      'no-else-return': 'off',
      'no-lonely-if': 'off',
      'no-nested-ternary': 'off',
      'no-useless-computed-key': 'off',
      'no-useless-rename': 'off',
      'object-shorthand': 'off',
      'prefer-object-spread': 'off',
      'no-useless-concat': 'off',
      'no-unmodified-loop-condition': 'off',
      'no-sequences': 'off',
      'no-void': 'off',
      'no-script-url': 'off',
      'no-new-wrappers': 'off',
      'no-multi-str': 'off',
      'no-native-reassign': 'off',
      'no-octal-escape': 'off',
      'no-constructor-return': 'off',
      'no-self-compare': 'off',
      'no-iterator': 'off',
      'no-proto': 'off',
      'no-caller': 'off',
      'no-alert': 'off',
      'no-implied-eval': 'off',
      'no-new-func': 'off',
      'no-param-reassign': 'off', // manager pattern mutates
      'no-shadow': 'off',
      'no-with': 'off',
      'max-nested-callbacks': 'off',
      'max-lines': ['error', { max: 3000, skipBlankLines: true, skipComments: true }],
      'no-use-before-define': ['error', { functions: false, classes: true, variables: true }],
      'wrap-iife': 'off',
      'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
      'no-trailing-spaces': 'error',
      'no-multi-spaces': ['error', { ignoreEOLComments: true }],
      'no-constant-condition': 'error',
      'no-cond-assign': ['error', 'always'],
      'no-unsafe-negation': 'error',
      'no-unreachable': 'error',
      'no-irregular-whitespace': 'error',
      'no-extra-semi': 'error',
      'eol-last': ['error', 'always'],
      'prefer-template': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-spread': 'error',
      'array-callback-return': 'error',
      'no-array-constructor': 'error',
      'no-new-object': 'error',
      'radix': 'error',
      'dot-notation': 'error',
      'curly': ['error', 'all'],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-throw-literal': 'error',
      'no-unused-expressions': 'error',
      'no-useless-return': 'error',
      'prefer-numeric-literals': 'error',
      'no-promise-executor-return': 'off',
      'no-unreachable-loop': 'error',
      'require-atomic-updates': 'off',
      'require-await': 'off',
      'no-setter-return': 'error',
      'no-return-await': 'error',
      'no-return-assign': 'error',
      'no-loop-func': 'off',
      'no-inner-declarations': 'error',
      'no-extra-label': 'error',
      'no-duplicate-imports': 'off',
      'no-compare-neg-zero': 'error',
      'no-case-declarations': 'off',
      'no-await-in-loop': 'off',
      'accessor-pairs': 'error',
      'spaced-comment': ['error', 'always', { exceptions: ['*', '/'] }],
      'capitalized-comments': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'id-denylist': 'off',
      'no-inline-comments': 'off',
      'no-restricted-exports': 'off',
      'no-restricted-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'sort-imports': 'off',
      'no-warning-comments': 'off',
      'no-empty-static-block': 'error',
      'logical-assignment-operators': 'off',
      'operator-assignment': 'error',
      'prefer-exponentiation-operator': 'error',
      'prefer-named-capture-group': 'off',
      'prefer-regex-literals': 'error',
      'require-unicode-regexp': 'off',
      'unicode-bom': 'off',
    },
  },
  prettier,
];
